use_frameworks!

platform :ios, '8.0'

target 'FFmpegKit_Example' do
  pod 'FFmpegKit', :path => '../'

  target 'FFmpegKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
